name: Test Suite

on: push

jobs:
  lint:
    name: Run Linter
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          cache: yarn
          node-version: 18

      - name: Install dependencies
        run: |
          yarn install --frozen-lockfile --prefer-offline
          yarn install --cwd example --frozen-lockfile --prefer-offline

      - name: Run linter
        run: yarn run lint
        id: lint

  type:
    name: Run Type Checker
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          cache: yarn
          node-version: 18

      - name: Install dependencies
        run: |
          yarn install --frozen-lockfile --prefer-offline
          yarn install --cwd example --frozen-lockfile --prefer-offline

      - name: Run type checker
        run: yarn run typescript
        id: type
